### ISSUE TITLE
errors.com.epicgames.common.throttled

### ISSUE THREAD

**Issue by eeeAAAkkk** [qlaffont/fortnite-api#146]
Anyone else trying to grab stats very often and get's this error?

 { StatusCodeError: 429 - {"errorCode":"errors.com.epicgames.common.throttled","errorMessage":"Operation access is limited by throttling policy, please try again in 8036 second(s).","messageVars":["8036"],"numericErrorCode":1041,"originatingService":"com.epicgames.account.public","intent":"prod"}

**Comment by eeeAAAkkk** [comment]
Hello @Jericho1060 ,

fully aware that this is not an issue with this project, just asking if someone had experience with this case.

I wrote a Discord Bot where users could grab there stats and some additional features. For our team members I wanted to create an extra feature where I grab the stats regularly to give them the option to show if they had a winstreak and their games with the highest kills.

Currently there are 8 users I want to grab the stats for, I do one .login and then loop over the users to get the stats. I started with a 3 minute intervall but already had some matches grouped together. Yes, if you die early in a round, there is a chance that the next match ends during that intervall. So I lowered to 2,5 minutes but had too many API calls after 12 hours. Maybe I should implement a counter to see how many calls I can have.

I wonder how sites like fortnitetracker get the stats for all the users.

**Comment by RobertoGraham** [comment]
Are you doing three stats calls per user, i.e. psn, xb1, and pc? You could fork this project to obtain all stats for every platform with just one API call.

**Comment by eeeAAAkkk** [comment]
@RobertoGraham which project do you mean?

I save the main platform for the user and therefor only have one api call per user. I'm thinking about getting a second account and switch after every logon to extend the limit.

**Comment by RobertoGraham** [comment]
@eeeAAAkkk I mean qlaffont/fortnite-api. Okay I see, but in the stats function there's a lookup call being made every time to get the account id. You can cache account ids against usernames, do a stats API call directly without the lookup and this will half your requests at least.

**Comment by eeeAAAkkk** [comment]
@RobertoGraham Understand, I already work with the fortnite user id, because names can change. So I can keep track of users/stats even if the name has changed.

What is the reason behind the lookup if we already have the id?

**Comment by eeeAAAkkk** [comment]
Ok, tracked the code a little bit. The lookup fills the user information in the returned stats. :-|

**Comment by Jericho1060** [comment]
@eeeAAAkkk 
> I wonder how sites like fortnitetracker get the stats for all the users.

**The following is only supposition** because i'm not working with fortnite tracker staff but it seems to be logic for me and **it's how i'm working with the api and never got that issue**.

In fact, for these API, they are working differently, they are not providing data directly from Epic Games.
They have a process querying the stats from the Epic Games api with a timer, i don't exactly know the frequence but it is maybe updated every hours for someone asking for stats and every 24h for a user that just checked one time but not checking a lot of time. Then, they are probably storing the result in there own database.
Where you are checking for stats using they own API, you are not querying Epic Games database but there own Database. That's why you don't meet such a problem.

By separating the two process, they can lower the amount of queries done on the Epic Games servers and avoid the problem you found.

**Comment by Jericho1060** [comment]
Maybe it's more clear with a drawing (i made it fast)
![fortnite api queries template](https://user-images.githubusercontent.com/28439359/48201059-527c2280-e361-11e8-870b-5df25dc78039.jpg)
