### ISSUE TITLE
API Rate Limit?

### ISSUE THREAD

**Issue by Emyrk** [qlaffont/fortnite-api#34]
Do you know what the api limit is before Epic stops letting you query?

**Comment by qlaffont** [comment]
Nop, i didn't have an issue of API Rate Limit !

**Comment by NickSuperb** [comment]
@qlaffont Any idea on what the token expiration is when you use this method?

**Comment by qlaffont** [comment]
You can check on index.js (CheckToken Method)

**Comment by Fyb3roptik** [comment]
That is not the resolution. They are currently rate limiting based on IP address and account

**Comment by Fyb3roptik** [comment]
```
2019/02/07 16:54:03 unsuccessful response returned: 429 {
  "errorCode" : "errors.com.epicgames.common.throttled",
  "errorMessage" : "Operation access is limited by throttling policy, please try again in 5588 second(s).",
  "messageVars" : [ "5588" ],
  "numericErrorCode" : 1041,
  "originatingService" : "com.epicgames.account.public",
  "intent" : "prod"
}
```

**Comment by T0TProduction** [comment]
We're building a web platform for gamers (flint.gg). Users are able to connect games to their profile, and we pull stats automatically. Currently we're doing this for Fortnite over a third-party API (fortniteapi.com), which has pretty high ratelimits >30,000 r / h
We would rather use a first-party API though, so when I found this I was wondering if we could switch. It seems the API we currently use uses this as source (as probably all do since there is no official public FN API ? ), so either they have a set of many accounts they rotate through using, or the ratelimit of this API is actually sufficient to supply millions of requests on new and already pulled data (which fortnite api has)

**Comment by Fyb3roptik** [comment]
Well, I got rate limited because I do the call every minute. We run real money contests using it. I think you will be fine and yes I rotate with 10 accounts, to combat it
