### ISSUE TITLE
Hi Qlaffont, can you check for me whether my params is ok?

### ISSUE THREAD

**Issue by jobsfan** [qlaffont/fortnite-api#90]
// require the package
const Fortnite = require("fortnite-api");

let fortniteAPI = new Fortnite(
    [
        "myemail@address.com",
        "mypassword",
        "eg1~eyJraWQiOiJ0RkMyVUloRnBUTV9FYTNxY09kX01xUVQxY0JCbTlrRkxTRGZlSmhzUkc4IiwiYWxnIjoiUFMyNTYifQ.eyJhcHAiOiJsYXVuY2hlciIsInN1YiI6ImU2ZGQ2ZGU0ZmE3ZTQzNWE5NDUxMmVkYTdmNzUwMjM1IiwicnNpZCI6IjhlMmJkYjM3ZDZjNzRkNGM4NzllMjc4NjRiMDZkNDYyIiwiY2xpZCI6IjM0YTAyY2Y4ZjQ0MTRlMjliMTU5MjE4NzZkYTM2ZjlhIiwiYW0iOiJleGNoYW5nZV9jb2RlIiwic3NpZCI6ImZlMzg2Nzg1NTk4NTQ3OTdiZGY0YzRmMjY2MmQ3MWE5IiwicCI6ImVOcWxWVTF2R2pFUVwvVCtJUTBrZ3RKWTRSRkhTSHFLbUtxMTZqQVo3bHJYdzJxN0hUa0pcL2ZjZUdKVVFDbG84VDdLNDk3ODJiTnpNK3pZeW1XdHU1OFBtdkZENDRsV1FVRWlMT1hWaE9Cb00rU09tU2plMlI5ckUzdWVvYlNGYldHSVJ5cjlZNFVHMEE3U3hcL3htUWdCcENMTFFTbHlSdFl3andnTnNoeDhFYXBHNFhEQ3NZNHZCN0JsK0ZvY0lVS3h0VjQ5T25xZXNSeFwvRjZlUUlSeE1oajFFM00yTGltS0xzQWNSU0ptMVJtYUwrNlBiWndFb1wvOUJTWVpQVmdHU0VsUkRRTTRUbHBsOWVUY1o3QkRDNkJmTTFER1FzeUNZWm1RTTJzaDNERGNHME5Hc1pEcjJudGk2UkxrRzc0XC84UkU1cU1DSWlOQ1FzY1JGdk52VmRcLzFJM1JJTVJGRVFRajdlXC92OTk5dVwvXC81UEowK1BUODlQR1RTczZTTjByWnlvdnhyd09vS2ljTjdMM3JDd0F4TjhVNFZORnBGUndteHg0S2dWRUIyQUIzeXlPRWlWOGxVMnBnaXo3amY0OVNJWUo0UG5zK0wyZXdoakc4Umd3VnptMkpOalBmV3NDak1uOWhpTEU0MzVJRk15SUtuMm1YMGJQNUh6WnAzaHl5bGtFNGhteG9ibjczZVdqeVwvd1lZeFA3VHgraU9cLzRhSnV1amdIWVVNWXR6blEyMWtURE1FRlByVWxVWFFMdE1KRjdwN3BTZ242bzJNOWhRYW5MZ1dKRHk3Y3JvWDkzT2ZNWHJSRWJSbmN5dHhodlkrTlQwdUt6SHIzOEdHM2VJNlB4eWp0QW92QzRrb201VUtiVm5uYnJhb015QUpkR3VWdjBuTHhneldvZ1hLd2RwZ2MzYW5GKzRIMVFzdWV4ZzE4VlRGOCtiQlZpTlA3XC80UXVaaitjTzZWWFY5Y0RkMk9rcmtzejdtcXVmSnVjd2dxU2lSMDdhK1hhaTVCMkl1UmxVR0tmTW1ET3lcL3NWak1GNGNHazJxRFRrelg2Uk9TdHVcL2YzZTVPM3BGc252Njg4aVJudlVBWTlEbm8wY3lzN3hWNTRIZHp5UmltR09uMlRGakZzYnVqT0JOZnpYNEpMUEcyVEdDMzlSd0xyYmFyaERYa3F6UnBjQmxxbTg3NVgydXl3NVhTYTZEXC9paThaWERuRFRqczl6XC9BYjJmWnQ0PSIsImlhaSI6ImU2ZGQ2ZGU0ZmE3ZTQzNWE5NDUxMmVkYTdmNzUwMjM1IiwiY2xzdmMiOiJsYXVuY2hlciIsImljIjp0cnVlLCJleHAiOjE1MjcxNzQ3NzksImlhdCI6MTUyNzE0NTk3OSwianRpIjoiYTVmYWFkMGYwZjY5NDFjOWE2M2I3YWE2ZjRkYzlmZGQifQ.Ajyo836zKKz0fLeb80LcPTS3tzmvjxHp2R9G7oVgBHVbzDA7lG8ENr7-5Dh2VbFAqxsTvZkRg4bB1qHyNFJ-eyz6",
        "eg1~eyJraWQiOiJ0RkMyVUloRnBUTV9FYTNxY09kX01xUVQxY0JCbTlrRkxTRGZlSmhzUkc4IiwiYWxnIjoiUFMyNTYifQ.eyJwIjoiZU5xVmtjRnF3ekFRUlBcL0g1RkE3cmhzditGUkNMcjMyQTliUzJoR3NWa1lycCszZlZ6RXVGR0pxZXBKWXpjeStRWXl6bUN0RnNPRkRPS0NGQXM2VE14ZjBwR1wvclkxY2QrdG14ZFRJRVdHNGV4UTJrQ1hDYXNtT1o1Vk1UcGxsMzVPOFNDZmtzb3hQNjJRQ01QVEVVMmNvYlJGdVdMUDMwT1U1SjFRWEpxbU9OVDVVWlRrTmRselZWYlY4K3QxVjVlbWtzSHB1aHhhNzhrK3VoOWc3VWdcLzQxU0NKSldXNHdJWWNSOUlxUjdKTHdyODFyMGk4QUV5emxLUEpUdXBkZGcrOFQ4bDE3MEdBY01pUkNyeUNhTGMwR003c2I3Y0lVVzdVTmg5bHFDaEZIQXYzU1JINFJLTVdiTStRa1wvN3dZMnJGMDFUZitsK1FZIiwiY2xzdmMiOiJsYXVuY2hlciIsImNsaWQiOiIzNGEwMmNmOGY0NDE0ZTI5YjE1OTIxODc2ZGEzNmY5YSIsImljIjp0cnVlLCJleHAiOjE1MjcxNjAzNzcsImFtIjoiY2xpZW50X2NyZWRlbnRpYWxzIiwiaWF0IjoxNTI3MTQ1OTc3LCJzc2lkIjoiZDUxODQ3NmE1YzVlNDkzZThkYTUyNmEwYTQ5MTY1ZGYiLCJqdGkiOiJkNTE4NDc2YTVjNWU0OTNlOGRhNTI2YTBhNDkxNjVkZiJ9.AJTyPphPtgtoCAjcIJyJBSao-PvMdDRzXokwd-yKWfSwMkaa1lTNRiZCRixyGvGPeSebx7lZYoipvvYhTB27N-yH"
    ],
    {
        debug: true
    }
);

fortniteAPI.login().then(() => {
    fortniteAPI
        .checkPlayer("Mirardes", "pc")
        .then(stats => {
            console.log(stats);
        })
        .catch(err => {
            console.log(err);
        });
});

I got a error message "UnhandledPromiseRejectionWarning: Please enter good token"
"UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)"

"DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code"

Looking forward to your reply.

**Comment by AHStudyBank** [comment]
+1

**Comment by RobertoGraham** [comment]
What happens if you use the payloads inside the JWTs instead?

 i.e:

launcherToken: `eNqlVU1vGjEQ/T+IQ0kgtJY4RFHSHqKmKq16jAZ7lrXw2q7HTkJ/fceGJUQClo8T7K49782bNzM+zYymWtu58PmvFD44lWQUEiLOXVhOBoM+SOmSje2R9rE3ueobSFbWGIRyr9Y4UG0A7Sx/xmQgBpCLLQSlyRtYwjwgNshx8EapG4XDCsY4vB7Bl+FocIUKxtV49OnqesRx/F6eQIRxMhj1E3M2LimKLsAcRSJm1RmaL+6PbZwEo/9BSYZPVgGSElRDQM4Tlpl9eTcZ7BDC6BfM1DGQsyCYZmQM2sh3DDcG0NGsZDr2nti6RLkG74/8RE5qMCIiNCQscRFvNvVd/1I3RIMRFEQQj7e/v999u//5PJ0+PT89PGTSs6SN0rZyovxrwOoKicN7L3rCwAxN8U4VNFpFRwmxx4KgVEB2AB3yyOEiV8lU2pgiz7jf49SIYJ4Pns+L2ewhjG8RgwVzm2JNjPfWsCjMn9hiLE435IFMyIKn2mX0bP5HzZp3hyylkE4hmxobn73eWjy/wYYxP7Tx+iO/4aJuujgHYUMYtznQ21kTDMEFPrUlUXQLtMJF7p7pSgn6o2M9hQanLgWJDy7croX93OfMXrREbRncytxhvY+NT0uKzHr38GG3eI6PxyjtAovC4kom5UKbVnnbraoMyAJdGuVv0nLxgzWogXKwdpgc3anF+4H1Qsuexg18VTF8+bBViNP7/4QuZj+cO6VXV9cDd2Okrksz7mqufJucwgqSiR07a+Xai5B2IuRlUGKfMmDOy/sVjMF4cGk2qDTkzX6ROStu/f3e5O3pFsnv688iRnvUAY9Dno0cys7xV54HdzyRimGOn2TFjFsbujOBNfzX4JLPG2TGC39RwLrbarhDXkqzRpcBlqm875X2uyw5XSa6D/ii8ZXDnDTjs9z/Ab2fZt4=`

clientToken: `eNqVkcFqwzAQRP/H5FA7rhsv+FRCLr32A9bS2hGsVkYrp+3fVzEuFGJqepJYzcy+QYyzmCtFsOFDOKCFAs6TMxf0pG/rY1cd+tmxdTIEWG4exQ2kCXCasmOZ5VMTpll35O8SCfksoxP62QCMPTEU2cobRFuWLP30OU5J1QXJqmONT5UZTkNdlzVVbV8+t1V5emksHpuhxa78k+uh9g7Ug/41SCJJWW4wIYcR9IqR7JLwr81r0i8AEyzlKPJTupddg+8T8l170GAcMiRCryCaLc0GM7sb7cIUW7UNh9lqChFHAv3SRH4RKMWbM+Qk/7wY2rF01Tf+l+QY`

**Comment by qlaffont** [comment]
You have all info in the Readme.Md. Your token is not good so respect the tutorial.
